import type { ServerResponse } from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";

const webRoot = path.dirname(fileURLToPath(import.meta.url));

/** Serve public/help/index.html at /help (Vite dev/preview otherwise SPA-fallback to index.html). */
function helpPageRoutePlugin() {
  const rewriteHelpUrl = (url: string | undefined): string | undefined => {
    const [pathname, search = ""] = (url ?? "").split("?");
    if (pathname === "/help" || pathname === "/help/") {
      return `/help/index.html${search ? `?${search}` : ""}`;
    }
    return url;
  };

  const install = (
    middlewares: { use: (fn: (req: { url?: string }, res: unknown, next: () => void) => void) => void },
  ) => {
    middlewares.use((req, _res, next) => {
      const nextUrl = rewriteHelpUrl(req.url);
      if (nextUrl && nextUrl !== req.url) req.url = nextUrl;
      next();
    });
  };

  return {
    name: "help-page-route",
    configureServer(server: { middlewares: Parameters<typeof install>[0] }) {
      install(server.middlewares);
    },
    configurePreviewServer(server: { middlewares: Parameters<typeof install>[0] }) {
      install(server.middlewares);
    },
  };
}

/** Swap dev /src CSS links in help/index.html for hashed production assets from index.html. */
function helpPageStylesPlugin() {
  const styleMarkerStart = "<!-- HELP_PAGE_STYLES -->";
  const styleMarkerEnd = "<!-- /HELP_PAGE_STYLES -->";

  return {
    name: "help-page-styles",
    closeBundle() {
      const distDir = path.resolve(webRoot, "dist");
      const mainIndexPath = path.join(distDir, "index.html");
      const helpIndexPath = path.join(distDir, "help", "index.html");
      if (!fs.existsSync(mainIndexPath) || !fs.existsSync(helpIndexPath)) return;

      const mainHtml = fs.readFileSync(mainIndexPath, "utf8");
      let helpHtml = fs.readFileSync(helpIndexPath, "utf8");

      const stylesheetLinks = [...mainHtml.matchAll(/<link[^>]+rel="stylesheet"[^>]*>/g)].map(
        (match) => match[0],
      );
      if (!stylesheetLinks.length) return;

      const start = helpHtml.indexOf(styleMarkerStart);
      const end = helpHtml.indexOf(styleMarkerEnd);
      if (start === -1 || end === -1) return;

      const replacement = `${styleMarkerStart}\n  ${stylesheetLinks.join("\n  ")}\n  ${styleMarkerEnd}`;
      helpHtml =
        helpHtml.slice(0, start) + replacement + helpHtml.slice(end + styleMarkerEnd.length);
      fs.writeFileSync(helpIndexPath, helpHtml, "utf8");
    },
  };
}

/**
 * Inject the committed prerendered landing snapshot into dist/index.html so the
 * deployed HTML contains real marketing content in `view-source:` (for crawlers,
 * link unfurlers, and compliance reviewers) instead of an empty "Loading…" shell.
 *
 * The snapshot is generated by scripts/prerender.mjs (headless Chrome) and lives
 * at prerendered/landing.snapshot.html. This plugin only reads that file with fs
 * — it pulls in NO browser and NO extra dependency — so Vercel builds stay fast
 * and can never fail on a missing/blocked Chromium download. On boot, main.ts's
 * render() replaces #app entirely, so the snapshot is a pure pre-hydration view.
 *
 * No-ops (with a warning) if the snapshot is missing so the build never breaks.
 */
function prerenderInjectPlugin() {
  return {
    name: "prerender-inject",
    closeBundle() {
      const indexPath = path.resolve(webRoot, "dist", "index.html");
      const snapshotPath = path.resolve(webRoot, "prerendered", "landing.snapshot.html");
      if (!fs.existsSync(indexPath)) return;
      if (!fs.existsSync(snapshotPath)) {
        console.warn(
          "[prerender-inject] prerendered/landing.snapshot.html missing — " +
            "shipping empty #app shell. Run `npm run prerender` to generate it.",
        );
        return;
      }

      const snapshot = fs.readFileSync(snapshotPath, "utf8");
      let html = fs.readFileSync(indexPath, "utf8");

      // Replace the empty mount node with one preloaded with the snapshot.
      const emptyApp = /<div id="app">\s*<\/div>/;
      if (!emptyApp.test(html)) {
        console.warn('[prerender-inject] could not find empty <div id="app"></div> — skipped.');
        return;
      }
      html = html.replace(emptyApp, `<div id="app">${snapshot}</div>`);
      fs.writeFileSync(indexPath, html, "utf8");
      console.log(`[prerender-inject] injected landing snapshot (${snapshot.length} bytes).`);
    },
  };
}

export default defineConfig({
  plugins: [helpPageRoutePlugin(), helpPageStylesPlugin(), prerenderInjectPlugin()],
  build: {
    // Guardrail: the critical landing entry must stay lean. The heavy voice SDK
    // (@elevenlabs/client, ~494 kB) is dynamically imported in main.ts so it
    // splits into its own on-demand chunk and stays off the first-paint path.
    // This limit sits just above that lazy chunk so normal builds are quiet, but
    // a regression that statically pulls the SDK back into the entry (~620 kB)
    // trips the warning instead of silently slowing the first page load.
    chunkSizeWarningLimit: 550,
  },
  resolve: {
    alias: {
      // Ensure browser voice session setup (mic/worklet/WebSocket) is registered in prod builds.
      "@elevenlabs/client": path.resolve(
        webRoot,
        "node_modules/@elevenlabs/client/dist/platform/web/index.js",
      ),
    },
  },
  server: {
    host: "127.0.0.1",
    port: 5173,
    proxy: {
      "/api": {
        target: "http://127.0.0.1:8780",
        changeOrigin: true,
        /** Vite/http-proxy default is HTTP 500 + empty body on ECONNREFUSED — unusable for debugging. */
        configure(proxy) {
          proxy.on("error", (err, _req, res) => {
            const r = res as ServerResponse | undefined;
            if (!r || r.headersSent) return;
            const msg =
              err instanceof Error ? err.message : String(err);
            r.writeHead(502, { "Content-Type": "application/json" });
            r.end(
              JSON.stringify({
                detail:
                  `Dev proxy could not reach the API at http://127.0.0.1:8780 (${msg}). ` +
                  "Start uvicorn from demo/realtime-sales-demo/server (see run-demo.ps1), then retry.",
              }),
            );
          });
        },
      },
      "/debug": {
        target: "http://127.0.0.1:8780",
        changeOrigin: true,
      },
      "/admin": {
        target: "http://127.0.0.1:8780",
        changeOrigin: true,
      },
    },
  },
});
